# 多维数组切片

In [5]:
import numpy as np
b = np.arange(24)
a = b.reshape((2, 3, 4))
print('原多维数组')
print(a)

原多维数组
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


如该三维数组，为2元3行4列形式。如果想获取某个元素，则需要 `a[1,2,3]` 的形式。

因此对于切片，第一个参数表示第几元，第二个参数表示第几行，第三个参数表示第几列。

如果为 `:` 则表示所有，`0:2`表示从0到2（不包含2）

In [7]:
print('数组a第0个元素（二维数组）下的所有子元素（一维数组）的第一列')
print(a[0, :, 0])   # 第0元，所有行的第一列元素

数组a第0个元素（二维数组）下的所有子元素（一维数组）的第一列
[0 4 8]


In [11]:
print('取所有二维数组下的每个二维数组的第0个元素（一维数组）')
print(a[:, 0])   # 所有元的第0行，由两个一维数组组成的二维数组

取所有二维数组下的每个二维数组的第0个元素（一维数组）
[[ 0  1  2  3]
 [12 13 14 15]]


In [12]:
print('取所有二维数组下面的所有一维数组的每一个一维数组的第0个元素')
print(a[:, :, 0])   # 所有元所有行的第0列元素

取所有二维数组下面的所有一维数组的每一个一维数组的第0个元素
[[ 0  4  8]
 [12 16 20]]


In [13]:
print('取所有二维数组下面的所有一维数组的每一个一维数组的第0到2（不包含第2）个元素')
print(a[:, :, 0:2])   # 所有元所有行的第0-2列元素

取所有二维数组下面的所有一维数组的每一个一维数组的第0到2（不包含第2）个元素
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
